include:
  - local: '.common-ci.yml'
  - project: nvidia/container-infrastructure/aws-kube-ci
    file: aws-kube-ci.yml
    ref: 20.05.05

integration_tests:
  stage: integration_tests
  image: alpine
  script:
    - source version
    - source aws-kube-ci/hostname
    - apk add --no-cache openssh-client
    - scp -i aws-kube-ci/key -r -o StrictHostKeyChecking=no ${CI_PROJECT_DIR} "${instance_hostname}:~/project"
    - ssh -i aws-kube-ci/key ${instance_hostname} \
      "cd ~/project/tests && ./ci-run-integration.sh ${CI_REGISTRY_IMAGE}:${VERSION}"
  dependencies:
    - aws_kube_setup
    - versionning

e2e_tests:
  stage: e2e_tests
  image: docker:dind
  services:
    - docker:dind
  script:
    - source version
    - source aws-kube-ci/hostname
    - apk add --no-cache openssh-client
    - scp -i aws-kube-ci/key -r -o StrictHostKeyChecking=no ${CI_PROJECT_DIR} "${instance_hostname}:~/project"
    - ssh -i aws-kube-ci/key ${instance_hostname} \
      "cd ~/project/tests && ./ci-run-e2e.sh ${CI_REGISTRY_IMAGE} ${VERSION} ${CI_COMMIT_TAG}"
  dependencies:
    - aws_kube_setup
    - versionning
