default:
  tags:
    - type/docker
    - docker/privileged
    - cnt
    - container-dev
    - os/linux

include:
  - local: '.common-ci.yml'

scan:
  extends: .scan
  script:
    - apk add --no-cache bash findutils libmagic curl make git
    - apk add --no-cache python3 python3-dev py3-pip py3-wheel
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab-master.nvidia.com/sectooling/scanning/contamer.git
    - cd contamer
    - pip3 install -r requirements.txt
    - docker tag ${CI_REGISTRY_IMAGE}:${VERSION} ${CI_PROJECT_NAME}:${VERSION}
    - python3 contamer.py -ls --fail-on-non-os ${CONTAMER_SUPPRESS_VULNS:+--suppress-vulns ${CONTAMER_SUPPRESS_VULNS}} -- ${CI_PROJECT_NAME}:${VERSION}

release:ngc:
  stage: deploy
  image: docker:dind
  services:
    - docker:dind
  before_script:
    - export NGC_REPO="${NGC_REGISTRY}/nvidia"
    - export NGC_PROD_IMAGE="${NGC_REPO}/${DOCKER_IMAGE_NAME}"
  script:
    - source version
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker pull ${CI_REGISTRY_IMAGE}:${VERSION}
    - docker tag ${CI_REGISTRY_IMAGE}:${VERSION} ${NGC_PROD_IMAGE}:${VERSION}
    - docker login -u ${NGC_REGISTRY_USER} -p ${NGC_REGISTRY_TOKEN} ${NGC_REGISTRY}
    - docker push ${NGC_PROD_IMAGE}:${VERSION}
  dependencies:
    - versionning
  only:
    - tags
