namespace:
  # Name of the namespace to put all components in
  name: node-feature-discovery
  # Specifies whether this namespace should be created or not
  create: true

worker:
  options: {}
  resources: {}
  securityContext: {}
  podSecurityContext: {}
  nodeSelector: {}
  annotations: {}
  tolerations: {}
  affinity: {}

master:
  extraLabelNs: []
  service:
    type: ClusterIP
    port: 8080

serviceAccount:
  # Name of the service account to use (whether existing or to be created)
  name: nfd-master
  # Specifies whether this service account should be created or not
  create: true
  # Annotations to add to the service account when creating it
  annotations: {}

rbac:
  # Role to associate with the service account above (whether existing to to be created)
  role: nfd-master
  # Specifies whether this role should be created or not
  create: true
