namespace:
  # Name of the namespace to put all components in
  name: node-feature-discovery
  # Specifies whether this namespace should be created or not
  create: true

worker:
  options: {}

master:
  extraLabelNs: []

serviceAccount:
  # Name of the service account to use (whether existing or to be created)
  name: nfd-master
  # Specifies whether this service account should be created or not
  create: true
  # Annotations to add to the service account when creating it
  annotations: {}
