failOnInitError: true
migStrategy: none
noTimestamp: false
sleepInterval: 60s

nameOverride: ""
fullnameOverride: ""

namespace: node-feature-discovery

imagePullSecrets: []
image:
  repository: nvcr.io/nvidia/gpu-feature-discovery
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

podSecurityContext: {}
securityContext:
  privileged: true

resources: {}
affinity: {}
tolerations: {}
nodeSelector:
  feature.node.kubernetes.io/pci-10de.present: "true" # NVIDIA vendor ID

runtimeClassName: null

nfd:
  deploy: true

node-feature-discovery:
  worker:
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
    - key: "nvidia.com/gpu"
      operator: "Equal"
      value: "present"
      effect: "NoSchedule"

    config:
      sources:
        pci:
          deviceClassWhitelist:
          - "02"
          - "0200"
          - "0207"
          - "0300"
          - "0302"
          deviceLabelFields:
          - vendor

  master:
    extraLabelNs:
      - nvidia.com

  serviceAccount:
    name: node-feature-discovery
