migStrategy: none
sleepInterval: 60s

nameOverride: ""
fullnameOverride: ""

nfd:
  deploy: true

node-feature-discovery:
  master:
    extraLabelNs:
      - nvidia.com
  worker:
    options:
      sources:
        pci:
          deviceLabelFields:
            - vendor

imagePullSecrets: []

image:
  repository: nvidia/gpu-feature-discovery
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

namespace: node-feature-discovery

podSecurityContext: {}
securityContext: {}

nodeSelector:
  feature.node.kubernetes.io/pci-10de.present: "true" # NVIDIA vendor ID

resources: {}

affinity: {}

tolerations: {}
